function [R1cut,p1cut] = f1cut(in1,in2,in3)
%F1CUT
%    [R1CUT,P1CUT] = F1CUT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Nov-2020 16:19:00

q31 = in1(30,:);
q32 = in1(31,:);
q33 = in1(32,:);
q34 = in1(33,:);
q35 = in1(34,:);
t2 = cos(q34);
t3 = cos(q35);
t4 = sin(q34);
t5 = sin(q35);
R1cut = reshape([t3,t4.*t5,-t2.*t5,0.0,t2,t4,t5,-t3.*t4,t2.*t3],[3,3]);
if nargout > 1
    p1cut = [q31;q32;q33];
end
