function out1 = RWRA_Position(in1,in2,in3)
%RWRA_POSITION
%    OUT1 = RWRA_POSITION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Nov-2020 16:16:34

R4cut1_1 = in3(28);
R4cut1_2 = in3(31);
R4cut1_3 = in3(34);
R4cut2_1 = in3(29);
R4cut2_2 = in3(32);
R4cut2_3 = in3(35);
R4cut3_1 = in3(30);
R4cut3_2 = in3(33);
R4cut3_3 = in3(36);
p4cut1 = in2(10);
p4cut2 = in2(11);
p4cut3 = in2(12);
q25 = in1(25,:);
q26 = in1(26,:);
q27 = in1(27,:);
t2 = cos(q25);
t3 = cos(q26);
t4 = cos(q27);
t5 = sin(q25);
t6 = sin(q26);
t7 = sin(q27);
t8 = R4cut1_1.*t2;
t9 = R4cut2_1.*t2;
t10 = R4cut3_1.*t2;
t11 = R4cut1_3.*t5;
t12 = R4cut2_3.*t5;
t13 = R4cut3_3.*t5;
t14 = -t11;
t15 = -t12;
t16 = -t13;
t17 = t8+t14;
t18 = t9+t15;
t19 = t10+t16;
out1 = [R4cut1_2.*(-3.4596e-1)+p4cut1-R4cut1_2.*t3.*2.792066666666667e-1+t6.*t17.*2.792066666666667e-1+t4.*(R4cut1_3.*t2+R4cut1_1.*t5).*(3.1e+1./6.25e+2)+t7.*(R4cut1_2.*t6+t3.*t17).*(3.1e+1./6.25e+2);R4cut2_2.*(-3.4596e-1)+p4cut2-R4cut2_2.*t3.*2.792066666666667e-1+t6.*t18.*2.792066666666667e-1+t4.*(R4cut2_3.*t2+R4cut2_1.*t5).*(3.1e+1./6.25e+2)+t7.*(R4cut2_2.*t6+t3.*t18).*(3.1e+1./6.25e+2);R4cut3_2.*(-3.4596e-1)+p4cut3-R4cut3_2.*t3.*2.792066666666667e-1+t6.*t19.*2.792066666666667e-1+t4.*(R4cut3_3.*t2+R4cut3_1.*t5).*(3.1e+1./6.25e+2)+t7.*(R4cut3_2.*t6+t3.*t19).*(3.1e+1./6.25e+2)];
